

#include "I2C_DriverLis3mdl.h"
#include "i2c.h"








//
// THIS FUNCTION ENABLES INTERRUPT ON INT PIN
//
// INTERRUPT ON INT PIN IS ENABLED BY SETTING THE IEN BIT OF INTERRUPT CONFIGURATION REGISTER 
//
// @author M USMAN
// Input:
// @param LIS3MDL_I2C_ADDRESS_WRITE : I2C BUS WRITE ADDRESS
// @param LIS3MDL_INT_CFG           : INTERRUPT CONFIGURATION REGISTER ADDRESS
// @param LIS3MDL_DATA8             : SPECIFYING 8 NUMBER OF BITS TO BE SENT ON 12C BUS
//
// Output: NA
// 
//
// @return 1 INTERRUPT IS ENABLED
// @return 0 INTERRUPT IS NOT ENABLED   
//
bool LIS3MDL_enableInterruptInt()
{
uint8_t LIS3MDL_INTE = 0x01;         // 8 Bit VALUE ENABLING INT PIN INTERRUPT

if(i2c_write(LIS3MDL_I2C_ADDRESS_WRITE,LIS3MDL_INT_CFG, LIS3MDL_DATA8,&LIS3MDL_INTE)!=STATUS_ERROR)
{
return true;    
}
else
{
    return false;
}

}

//
// THIS FUNCTION DISABLES INTERRUPT ON INT PIN
//
// INTERRUPT ON INT PIN IS DISABLED BY RESETTING THE IEN BIT OF INTERRUPT CONFIGURATION REGISTER 
//
// @author M USMAN
// Input:
// @param LIS3MDL_I2C_ADDRESS_WRITE : I2C BUS WRITE ADDRESS
// @param LIS3MDL_INT_CFG           : INTERRUPT CONFIGURATION REGISTER ADDRESS
// @param LIS3MDL_DATA8             : SPECIFYING 8 NUMBER OF BITS TO BE SENT ON 12C BUS
//
// Output: NA
// 
//
// @return 1 INTERRUPT IS DISABLED
// @return 0 INTERRUPT IS NOT DISABLED
//
bool LIS3MDL_disableInterruptInt()
{
uint8_t LIS3MDL_INTD = 0x00;          // 8 Bit VALUE DISABLING INT PIN INTERRUPT
if(i2c_write(LIS3MDL_I2C_ADDRESS_WRITE,LIS3MDL_INT_CFG, LIS3MDL_DATA8,&LIS3MDL_INTD)!=STATUS_ERROR)
{
return true;    
}
else
{
    return false;
}

}





